// //MISC
// export const GET_RESPONSE_STATUS = "GET_RESPONSE_STATUS"
// export const MILESTONES_RESPONSE_STATUS = "MILESTONES_RESPONSE_STATUS"
// export const CONCERNS_RESPONSE_STATUS = "CONCERNS_RESPONSE_STATUS"
// export const SUGGESTIONS_RESPONSE_STATUS = "SUGGESTIONS_RESPONSE_STATUS"
// export const MILESTONES_POST_DATA = "MILESTONES_POST_DATA"
// export const SET_DEFAULT_STATES = "SET_DEFAULT_STATES"
// export const POST_FEEDBACK_SUCCESS = "POST_FEEDBACK_SUCCESS"


//DASHBOARD
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS"
export const GET_USER_INFO_ERRORED = "GET_USER_INFO_ERRORED"
export const GET_USER_INFO_LOADING = "GET_USER_INFO_LOADING"


//login
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGIN_LOADING = "LOGIN_LOADING"
export const LOGIN_SUCCESS = "LOGIN SUCCESS"


//logout
export const LOGOUT_ERROR = "LOGOUT_ERROR"
export const LOGOUT_LOADING = "LOGOUT_LOADING"
export const LOGOUT_SUCCESS = "LOGOUT SUCCESS"


//signups
export const SIGNUP_LOADING = "SIGNUP_LOADING"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_ERROR = "SIGNUP_ERROR"


//course list

export const GET_USER_COURSES_SUCCESS = "GET_USER_COURSES_SUCCESS"
export const GET_USER_COURSES_ERRORED = "GET_USER_COURSES_ERRORED"
export const GET_USER_COURSES_LOADING = "GET_USER_COURSES_LOADING"


//course
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS"
export const CREATE_COURSE_ERRORED = "CREATE_COURSE_ERRORED"
export const CREATE_COURSE_LOADING = "CREATE_COURSE_LOADING"

export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS"
export const DELETE_COURSE_ERRORED = "DELETE_COURSE_ERRORED"
export const DELETE_COURSE_LOADING = "DELETE_COURSE_LOADING"

export const EDIT_COURSE_SUCCESS = "EDIT_COURSE_SUCCESS"
export const EDIT_COURSE_ERRORED = "EDIT_COURSE_ERRORED"
export const EDIT_COURSE_LOADING = "EDIT_COURSE_LOADING"


//lecture list
export const GET_BOARDS_SUCCESS = "GET_BOARDS_SUCCESS"
export const GET_BOARDS_ERRORED = "GET_BOARDS_ERRORED"
export const GET_BOARDS_LOADING = "GET_BOARDS_LOADING"

//lecture
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS"
export const CREATE_BOARD_ERRORED = "CREATE_BOARD_ERRORED"
export const CREATE_BOARD_LOADING = "CREATE_BOARD_LOADING"

export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS"
export const DELETE_BOARD_ERRORED = "DELETE_BOARD_ERRORED"
export const DELETE_BOARD_LOADING = "DELETE_BOARD_LOADING"

export const EDIT_BOARD_SUCCESS = "EDIT_BOARD_SUCCESS"
export const EDIT_BOARD_ERRORED = "EDIT_BOARD_ERRORED"
export const EDIT_BOARD_LOADING = "EDIT_BOARD_LOADING"


//organization
export const CREATE_ORGANIZATION_SUCCESS = "CREATE_ORGANIZATION_SUCCESS"
export const CREATE_ORGANIZATION_ERRORED = "CREATE_ORGANIZATION_ERRORED"
export const CREATE_ORGANIZATION_LOADING = "CREATE_ORGANIZATION_LOADING"

export const DELETE_ORGANIZATION_SUCCESS = "DELETE_ORGANIZATION_SUCCESS"
export const DELETE_ORGANIZATION_ERRORED = "DELETE_ORGANIZATION_ERRORED"
export const DELETE_ORGANIZATION_LOADING = "DELETE_ORGANIZATION_LOADING"




    // organization: organizationReducer,
    // user: userReducer

//forgot password
export const EMAIL_LOADING = "EMAIL_LOADING"
export const EMAIL_SUCCESS = "EMAIL_SUCCESS"
export const EMAIL_ERROR = "EMAIL_ERROR"
export const DATABASE_UPDATING = "DATABASE_UPDATING"
export const DATABASE_UPDATED = "DATABASE_UPDATED"
export const UPDATE_ERROR = "UPDATE_ERROR"
export const GET_URL = "GET_URL"
export const INCORRECT_MAIL = "INCORRECT_MAIL"
export const SET_DEFAULTS = "SET_DEFAULTS"

export const GET_LOCATION = "GET_LOCATION"
export const GET_TEMPERATURE_SUCCESS = "GET_TEMPERATURE_SUCCESS"
export const GET_DASHBOARD_ANALYTICS = "GET_DASHBOARD_ANALYTICS"
export const GET_DASHBOARD_VACCINE_SUCCESS = "GET_DASHBOARD_VACCINE_SUCCESS"
export const GET_DASHBOARD_ANALYTICS_LOADING = "GET_DASHBOARD_ANALYTICS_LOADING"

export const RESET_STORE = "RESET_STORE"
export const RESET_REDUX_STORE_DELETE = "RESET_REDUX_STORE_DELETE"

/*
// Reminder
export const REMINDER_LOADING = "REMINDER_LOADING"
export const REMINDER_DATA_SUCCESS = "REMINDER_DATA_SUCCESS"
export const REMINDER_HAS_ERRORED = "REMINDER_HAS_ERRORED"

//Milestones
export const MILESTONES_LOADING = "MILESTONES_LOADING"
export const MILESTONES_DATA_SUCCESS = "MILESTONES_DATA_SUCCESS"
export const MILESTONES_HAS_ERRORED = "MILESTONES_HAS_ERRORED"
export const MILESTONES_HAS_CHANGED = "MILESTONES_HAS_CHANGED"
export const MILESTONES_INIT_CHANGED = "MILESTONES_INIT_CHANGED"

//Concerns
export const CONCERNS_LOADING = "CONCERNS_LOADING"
export const CONCERNS_DATA_SUCCESS = "CONCERNS_DATA_SUCCESS"
export const CONCERNS_HAS_ERRORED = "CONCERNS_HAS_ERRORED"
export const CONCERNS_HAS_CHANGED = "CONCERNS_HAS_CHANGED"
export const CONCERNS_INIT_CHANGED = "CONCERNS_INIT_CHANGED"
export const CONCERNS_POST_DATA = "CONCERNS_POST_DATA"


//Suggestions
export const SUGGESTIONS_LOADING = "SUGGESTIONS_LOADING"
export const SUGGESTIONS_DATA_SUCCESS = "SUGGESTIONS_DATA_SUCCESS"
export const SUGGESTIONS_HAS_ERRORED = "SUGGESTIONS_HAS_ERRORED"
export const SUGGESTIONS_HAS_CHANGED = "SUGGESTIONS_HAS_CHANGED"

//Growth
export const GROWTH_CHART_LOADING = "GROWTH_CHART_LOADING"
export const GROWTH_CHART_DATA_SUCCESS = "GROWTH_CHART_DATA_SUCCESS"
export const GROWTH_CHART_HAS_ERRORED = "GROWTH_CHART_HAS_ERRORED"
export const GROWTH_CHART_HAS_CHANGED = "GROWTH_CHART_HAS_CHANGED"
export const GROWTH_CHART_TYPE_CHANGE = "GROWTH_CHART_TYPE_CHANGE"
export const GROWTH_CHART_EDIT_DATA = "GROWTH_CHART_EDIT_DATA"
export const GROWTH_CHART_ADD_DATA = "GROWTH_CHART_ADD_DATA"
export const GROWTH_CHART_DELETE_DATA = "GROWTH_CHART_DELETE_DATA"
export const HELP_DATA_SUCCESS = "HELP_DATA_SUCCESS"
export const GROWTH_CHART_HELP_DATA_LOADING = "GROWTH_CHART_HELP_DATA_LOADING"

//login
export const PERSISTENT_LOGIN = "PERSISTENT_LOGIN"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGIN_LOADING = "LOGIN_LOADING"
export const ERROR_FOUND = "ERROR_FOUND"
export const LOGIN_NETWORK_ERROR = "LOGIN_NETWORK_ERROR"

//signups
export const SIGNUP_LOADING = "SIGNUP_LOADING"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_ERROR = "SIGNUP_ERROR"
export const SIGNUP_DISPLAY_ERROR = "SIGNUP_DISPLAY_ERROR"
export const UPLOAD_PHONE_NUMBER = "UPLOAD_PHONE_NUMBER"

//forgot password
export const EMAIL_LOADING = "EMAIL_LOADING"
export const EMAIL_SUCCESS = "EMAIL_SUCCESS"
export const EMAIL_ERROR = "EMAIL_ERROR"
export const DATABASE_UPDATING = "DATABASE_UPDATING"
export const DATABASE_UPDATED = "DATABASE_UPDATED"
export const UPDATE_ERROR = "UPDATE_ERROR"
export const GET_URL = "GET_URL"
export const INCORRECT_MAIL = "INCORRECT_MAIL"
export const SET_DEFAULTS = "SET_DEFAULTS"

//Prescriptions
export const PRESCRIPTIONS_IMAGE_UPLOAD = "PRESCRIPTIONS_IMAGE_UPLOAD"
export const PRESCRIPTIONS_IMAGE_DELETE = "PRESCRIPTIONS_IMAGE_DELETE"
export const PRESCRIPTIONS_ADD_PRESCRIPTION  = "PRESCRIPTIONS_ADD_PRESCRIPTION"
export const PRESCRIPTIONS_VIEW_PRESCRIPTION = "PRESCRIPTIONS_VIEW_PRESCRIPTION"
export const PRESCRIPTIONS_LOADING = "PRESCRIPTIONS_LOADING"
export const PRESCRIPTIONS_DATA_SUCCESS = "PRESCRIPTIONS_DATA_SUCCESS"
export const PRESCRIPTIONS_HAS_ERRORED = "PRESCRIPTIONS_HAS_ERRORED"
export const PRESCRIPTIONS_PRESCRIPTION_LOADING = "PRESCRIPTIONS_PRESCRIPTION_LOADING"
export const PRESCRIPTIONS_PRESCRIPTION_HAS_ERRORED = "PRESCRIPTIONS_PRESCRIPTION_HAS_ERRORED"
export const PRESCRIPTIONS_PRESCRIPTION_DATA_SUCCESS = "PRESCRIPTIONS_PRESCRIPTION_DATA_SUCCESS"
export const PRESCRIPTIONS_DELETE_IMAGE_BEFORE= "PRESCRIPTIONS_DELETE_IMAGE_BEFORE"
export const PRESCRIPTIONS_EDIT_IMAGE = "PRESCRIPTIONS_EDIT_IMAGE"
export const PRESCRIPTIONS_PRESCRIPTIONS_DELETE_IMAGE = "PRESCRIPTIONS_PRESCRIPTIONS_DELETE_IMAGE"
export const PRESCRIPTIONS_PRESCRIPTIONS_VIEW_IMAGE = "PRESCRIPTIONS_PRESCRIPTIONS_VIEW_IMAGE"
export const PRESCRIPTIONS_HAS_CHANGED = "PRESCRIPTIONS_HAS_CHANGED"
export const PRESCRIPTIONS_CLEAR_IMAGES = "PRESCRIPTIONS_CLEAR_IMAGES"
export const PRESCRIPTIONS_CHANGE_TYPE = "PRESCRIPTIONS_CHANGE_TYPE"
export const PRESCRIPTIONS_ADD_DETAILS = "PRESCRIPTIONS_ADD_DETAILS"
export const PRESCRIPTIONS_ADD_UPLOADING_PRESCRIPTION = "PRESCRIPTIONS_ADD_UPLOADING_PRESCRIPTION"
export const PRESCRIPTIONS_CLEAR_UPLOADING_PRESCRIPTIONS = "PRESCRIPTIONS_CLEAR_UPLOADING_PRESCRIPTIONS"
export const PRESCRIPTIONS_VIEW_UPLOADING_PRESCRIPTION = "PRESCRIPTIONS_VIEW_UPLOADING_PRESCRIPTION"

export const FETCH_INDEX = "FETCH_INDEX"

//add vaccines
export const VACCINE_ADD_HAS_ERRORED = "VACCINE_ADD_HAS_ERRORED"
export const VACCINE_ADD_LOADING = "VACCINE_ADD_LOADING"
export const VACCINE_ADD_SUCCESS = "VACCINE_ADD_SUCCESS"

//show vaccines
export const SHOW_VACCINE_LOADING="SHOW_VACCINE_LOADING"
export const SHOW_VACCINE_SUCCESS="SHOW_VACCINE_SUCCESS"
export const SHOW_VACCINE_HAS_ERRORED ="SHOW_VACCINE_HAS_ERRORED"
export const SHOW_VACCINE_HAS_CHANGED = "SHOW_VACCINE_HAS_CHANGED"

//show vaccine details
export const VACCINE_INFO_HAS_ERRORED ="VACCINE_INFO_HAS_ERRORED"
export const VACCINE_INFO_LOADING="VACCINE_INFO_LOADING"
export const VACCINE_INFO_SUCCESS= "VACCINE_INFO_SUCCESS"

//generate user
export const UPLOAD_CHILD_DETAILS = "UPLOAD_CHILD_DETAILS"
export const UPLOAD_GENDER = "UPLOAD_GENDER"
export const UPLOAD_ACC_ID = "UPLOAD_ACC_ID"
export const UPLOAD_USER_ID = "UPLOAD_USER_ID"
export const CHANGE_USER = "CHANGE_USER"
export const INIT_USER = "INIT_USER"
export const RESET_STORE = "RESET_STORE"
export const CLEAR_NAMES = "CLEAR_NAMES"
export const UPLOAD_AUTH_DETAILS = "UPLOAD_AUTH_DETAILS"
export const CREATE_ADULT_USER_SUCCESS = "CREATE_ADULT_USER_SUCCESS"
export const UPLOAD_ADULT_DETAILS = "UPLOAD_ADULT_DETAILS"
export const RESET_ADULT_STORE = "RESET_ADULT_STORE"
export const ADULT_USER_ERRORED = "ADULT_USER_ERRORED"
export const CREATING_ADULT_USER = "CREATING_ADULT_USER"
export const CREATING_CHILD_USER = "CREATING_CHILD_USER"
export const UPLOAD_ADULT_USER_ID = "UPLOAD_ADULT_USER_ID"
export const EDIT_ADULT_PROFILE_PIC = "EDIT_ADULT_PROFILE_PIC"
export const ADULT_PROFILE_PIC_HAS_CHANGED = "ADULT_PROFILE_PIC_HAS_CHANGED"

//vaccine list  
export const VACCINE_LIST_HAS_ERRORED = "VACCINE_LIST_HAS_ERRORED"
export const VACCINE_LIST_LOADING = "VACCINE_LIST_LOADING"
export const VACCINE_LIST_SUCCESS = "VACCINE_LIST_SUCCESS"
export const GET_TIME = "GET_TIME"
export const VACCINE_DELETE_SUCCESS = "VACCINE_DELETE_SUCCESS"
export const DELETE_PRESSED = "DELETE_PRESSED"
export const VACCINE_DELETE_LOADING = "VACCINE_DELETE_LOADING"

//bills
export const BILL_IMAGE_UPLOAD = "BILL_IMAGE_UPLOAD"
export const BILL_IMAGE_DELETE = "BILL_IMAGE_DELETE"
export const BILL_ADD_PRESCRIPTION = "BILL_ADD_PRESCRIPTION" 
export const BILL_PRESCRIPTION_DATA_SUCCESS = "BILL_PPRESCRIPTION_DATA_SUCCESS"
export const BILL_PRESCRIPTION_HAS_ERRORED = "BILL_PPRESCRIPTION_HAS_ERRORED"
export const BILL_PRESCRIPTION_LOADING = "BILL_PPRESCRIPTION_LOADING"
export const BILL_DATA_SUCCESS = "BILL_DATA_SUCCESS"
export const BILL_HAS_ERRORED = "BILL_HAS_ERRORED"
export const BILL_LOADING = "BILL_LOADING"
export const BILL_DELETE_IMAGE_BEFORE = "BILL_DELETE_IMAGE_BEFORE"
export const BILL_EDIT_IMAGE = "BILL_EDIT_IMAGE"
export const BILL_PRESCRIPTIONS_DELETE_IMAGE = "BILL_PPRESCRIPTIONS_DELETE_IMAGE"
export const BILL_PRESCRIPTIONS_VIEW_IMAGE = "BILL_PPRESCRIPTIONS_VIEW_IMAGE"
export const BILL_HAS_CHANGED = "BILL_HAS_CHANGED"
export const BILL_CLEAR_IMAGES = "BILL_CLEAR_IMAGES"
export const BILL_CHANGE_TYPE = "BILL_CHANGE_TYPE"
export const BILL_ADD_DETAILS = "BILL_ADD_DETAILS"
export const BILL_ADD_UPLOADING_PRESCRIPTION = "BILL_ADD_UPLOADING_PRESCRIPTION"
export const BILL_CLEAR_UPLOADING_PRESCRIPTION = "BILL_CLEAR_UPLOADING_PRESCRIPTION"
export const BILL_VIEW_UPLOADING_PRESCRIPTION = "BILL_VIEW_UPLOADING_PRESCRIPTION"

//Reports

export const REPORTS_IMAGE_UPLOAD = "REPORTS_IMAGE_UPLOAD"
export const REPORTS_IMAGE_DELETE = "REPORTS_IMAGE_DELETE"
export const REPORTS_ADD_PRESCRIPTION  = "REPORTS_ADD_PRESCRIPTION"
export const REPORTS_VIEW_PRESCRIPTION = "REPORTS_VIEW_PRESCRIPTION"
export const REPORTS_LOADING = "REPORTS_LOADING"
export const REPORTS_DATA_SUCCESS = "REPORTS_DATA_SUCCESS"
export const REPORTS_HAS_ERRORED = "REPORTS_HAS_ERRORED"
export const PRESCRIPTION_LOADING = "PRESCRIPTION_LOADING"
export const PRESCRIPTION_HAS_ERRORED = "PRESCRIPTION_HAS_ERRORED"
export const PRESCRIPTION_DATA_SUCCESS = "PRESCRIPTION_DATA_SUCCESS"
export const REPORTS_DELETE_IMAGE_BEFORE= "REPORTS_DELETE_IMAGE_BEFORE"
export const REPORTS_EDIT_IMAGE = "REPORTS_EDIT_IMAGE"
export const PRESCRIPTIONS_DELETE_IMAGE = "PRESCRIPTIONS_DELETE_IMAGE"
export const PRESCRIPTIONS_VIEW_IMAGE = "PRESCRIPTIONS_VIEW_IMAGE"
export const REPORTS_HAS_CHANGED = "REPORTS_HAS_CHANGED"
export const REPORTS_CLEAR_IMAGES = "REPORTS_CLEAR_IMAGES"
export const REPORTS_CHANGE_TYPE = "REPORTS_CHANGE_TYPE"
export const REPORTS_ADD_DETAILS = "REPORTS_ADD_DETAILS"
export const REPORTS_ADD_UPLOADING_PRESCRIPTION = "REPORTS_ADD_UPLOADING_PRESCRIPTION"
export const REPORTS_CLEAR_UPLOADING_PRESCRIPTIONS = "REPORTS_CLEAR_UPLOADING_PRESCRIPTIONS"
export const REPORTS_VIEW_UPLOADING_PRESCRIPTION = "REPORTS_VIEW_UPLOADING_PRESCRIPTION"

//Documents
export const DOCUMENTS_IMAGE_UPLOAD = "DOCUMENTS_IMAGE_UPLOAD"
export const DOCUMENTS_IMAGE_DELETE = "DOCUMENTS_IMAGE_DELETE"
export const DOCUMENTS_ADD = "DOCUMENTS_ADD"
export const DOCUMENTS_LOADING = "DOCUMENTS_LOADING"
export const DOCUMENTS_DATA_SUCCESS = "DOCUMENTS_DATA_SUCCESS"
export const DOCUMENTS_HAS_ERRORED = "DOCUMENTS_HAS_ERRORED"
export const DOCUMENTS_DOCUMENT_LOADING = "DOCUMENTS_DOCUMENT_LOADING"
export const DOCUMENTS_DOCUMENT_HAS_ERRORED = "DOCUMENTS_DOCUMENT_HAS_ERRORED"
export const DOCUMENTS_DOCUMENT_DATA_SUCCESS = "DOCUMENTS_DOCUMENT_DATA_SUCCESS"
export const DOCUMENTS_DELETE_IMAGE_BEFORE = "DOCUMENTS_DELETE_IMAGE_BEFORE"
export const DOCUMENTS_EDIT_IMAGE = "DOCUMENTS_EDIT_IMAGE"
export const DOCUMENTS_DELETE_IMAGE = "DOCUMENTS_DELETE_IMAGE"
export const DOCUMENTS_VIEW_IMAGE= "DOCUMENTS_VIEW_IMAGE"
export const DOCUMENTS_HAS_CHANGED = "DOCUMENTS_HAS_CHANGED"
export const DOCUMENTS_CLEAR_IMAGES = "DOCUMENTS_CLEAR_IMAGES"
export const DOCUMENTS_CHANGE_TYPE = "DOCUMENTS_CHANGE_TYPE"
export const DOCUMENTS_ADD_DETAILS = "DOCUMENTS_ADD_DETAILS"
export const DOCUMENTS_ADD_UPLOADING_DOCUMENT = "DOCUMENTS_ADD_UPLOADING_DOCUMENT"
export const DOCUMENTS_CLEAR_UPLOADING_DOCUMENTS = "DOCUMENTS_CLEAR_UPLOADING_DOCUMENTS"
export const DOCUMENTS_VIEW_UPLOADING_DOCUMENT = "DOCUMENTS_VIEW_UPLOADING_DOCUMENT"
export const DOCUMENTS_CHANGE_DOC_TYPE = "DOCUMENTS_CHANGE_DOC_TYPE"
export const DOCUMENTS_SET_FILTER = "DOCUMENTS_SET_FILTER"
export const DOCUMENTS_SET_UPDATED = "DOCUMENTS_SET_UPDATED"
export const DOCUMENTS_SET_DOCUMENTS = "DOCUMENTS_SET_DOCUMENTS"
export const DOCUMENTS_ADDING_IMAGE = "DOCUMENTS_ADDING_IMAGE"
export const DOCUMENTS_GET_IMAGES_SUCCESS = "DOCUMENTS_GET_IMAGES_SUCCESS"
export const DOCUMENTS_GET_FIRST_IMAGES_SUCCESS = "DOCUMENTS_GET_FIRST_IMAGES_SUCCESS"

//show medicine
export const SHOW_MEDICINE_LOADING = "SHOW_MEDICINE_LOADING"
export const SHOW_MEDICINE_SUCCESS = "SHOW_MEDICINE_SUCCESS"
export const SHOW_MEDICINE_HAS_ERRORED = "SHOW_MEDICINE_HAS_ERRORED"
export const MEDICINE_GET_RESPONSE_STATUS = "MEDICINE_GET_RESPONSE_STATUS"
export const GET_REMINDERS_SUCCESS = "GET_REMINDERS_SUCCESS"
export const GET_REMINDERS_LOADING = "GET_REMINDERS_LOADING"
export const REMINDER_MARKED_DONE = "REMINDER_MARKED_DONE"
export const REMINDER_DELETE_SUCCESS = "REMINDER_DELETE_SUCCESS"
export const REMINDER_EDIT_SUCCESS = "REMINDER_EDIT_SUCCESS"
export const REMINDER_GET_HISTORY = "REMINDER_GET_HISTORY"
export const MEDICINE_ADDED = "MEDICINE ADDED"
export const MEDICINE_REMINDER_DELETING = "MEDICINE_REMINDER_DELETING"
export const MEDICINE_SEARCH_RESULTS_SUCCESS = "MEDICINE_SEARCH_RESULTS_SUCCESS"

//faq
export const SHOW_FAQ_LOADING = "SHOW_FAQ_LOADING"
export const SHOW_FAQ_SUCCESS = "SHOW_FAQ_SUCCESS"
export const SHOW_FAQ_HAS_ERRORED = "SHOW_FAQ_HAS_ERRORED"
export const SHOW_FAQ_BACK = "SHOW_FAQ_BACK"

//security
export const TWO_STEP_VERIFICATION_CHANGED = "TWO_STEP_VERIFICATION_CHANGED"
export const NAME_HAS_CHANGED = "NAME_HAS_CHANGED"
export const GENDER_HAS_CHANGED = "GENDER_HAS_CHANGED"
export const DOB_HAS_CHANGED = "DOB_HAS_CHANGED"
export const NUMBER_HAS_CHANGED = "NUMBER_HAS_CHANGED"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const TWO_STEP_ENABLED = "TWO_STEP_ENABLED"
export const OTP_VERIFIED = "OTP_VERIFIED"
export const SEND_LOGIN_OTP_SUCCESS = "SEND_LOGIN_OTP_SUCCESS"
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS"
export const RESET_REDUX_STORE_DELETE = "RESET_REDUX_STORE_DELETE"
export const RESEND_OTP = "RESEND_OTP"





// NEW REGISTRATION
export const USER_SIGNUP_LOADING = "USER_SIGNUP_LOADING"
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_SIGNUP_LOADING_DONE = "USER_SIGNUP_LOADING_DONE"
export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING"
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_LOADING_DONE = "USER_LOGIN_LOADING_DONE"

// OTP NEW REGISTRATION
export const OTP_LOADING = "OTP_LOADING"
export const OTP_ERROR = "OTP_ERROR" 
export const OTP_SUCCESS = "OTP_SUCCESS"
export const SETUP_TOKEN_AFTER_OTP = "SETUP_TOKEN_AFTER_OTP"

// DASHBOARD
export const ADD_IMAGE_TO_MOMENTS = "ADD_IMAGE_TO_MOMENTS"
export const GET_PRECIOUS_MOMENTS_SUCCESS = "GET_PRECIOUS_MOMENTS_SUCCESS"
export const GET_TIPS_SUCCESS = "GET_TIPS_SUCCESS"
export const DID_YOU_KNOW_FETCH_SUCCESS = "DID_YOU_KNOW_FETCH_SUCCESS"
export const DASHBOARD_CALLS_START = "DASHBOARD_CALLS_START"
export const PROFILE_CALLS_START = "PROFILE_CALLS_START"
*/